### ISSUE TITLE
[feature] Instruction for install with plug

### ISSUE THREAD

**Issue by zodman** [synaptiko/xit.nvim#1]
I added:

```
 Plug 'synaptiko/xit.nvim'
Plug 'synaptiko/tree-sitter-xit'

```

and it don't work :(

**Comment by raine** [comment]
Same issue. Not sure what exactly is required.

**Comment by buraksirma** [comment]
Could you guys try the steps below?

1. Add these packages to your vimrc.
```
Plug 'synaptiko/xit.nvim' 
Plug 'nvim-treesitter/nvim-treesitter'
```
2. Reload neovim and run ```:PlugInstall```
3. Initialize the xit.nvim package in your configs.
    1. If you are using vimrc still just paste ```lua require('xit').setup({})```
    2. If you are using lua based configs just use ```require('xit').setup({})```
4. Open a xit file and run ```:TSInstall! xit```

**Comment by Yettimania** [comment]
Executing step 3 above I got following error:

```bash
E5108: Error executing lua vim/shared.lua:262: after the second argument: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:662: in function 'validate'
        vim/shared.lua:262: in function 'tbl_deep_extend'
        ...e/ksnyder/.config/nvim/plugged/xit.nvim/lua/xit/init.lua:299: in function 'setup'
        [string ":lua"]:1: in main chunk
```

**Comment by elcih17** [comment]
Changing `require('xit').setup()` to `require('xit').setup({})` should solve the problem.

**Comment by hern42** [comment]
hi,
i followed this procedure and everything works fine (ie no error, no bug) but i do not see any difference in the xit file (no syntax highlight for instance, and the shortcuts don't work.).
however, i use the .config/nvim/init.vim file for the Plug commands... not the .vimrc
could it be the issue?

**Comment by synaptiko** [comment]
Should be fixed now. Thanks guys.
